[Dark Mode] Map color segmentation for showing full gray scale map on background but keeping the colored layers
GNimrodG/simrail-map-optimized pull request #22
Opened 2024-06-19 11:34 UTC by EMREOYUN

Inspired by the simrail.app map. However, the major change is speed and infrastructure layers keep their colors. This code only works on dark mode.

Before:
![opera_1Mo1WDksVi](https://github.com/GNimrodG/simrail-map-optimized/assets/35144629/076d2dbc-9259-423f-bc90-4086b65053e4)

How it looks on simrail.app:
![image](https://github.com/GNimrodG/simrail-map-optimized/assets/35144629/eb032947-f336-445c-8888-e7536f3f5765)

After:
![opera_FC4aKhu4TS](https://github.com/GNimrodG/simrail-map-optimized/assets/35144629/799fd93f-8c96-46c6-8833-0d2bd22a99f6)

2024-06-19 11:50 UTC, GNimrodG commented
Hi,
It was intentional design on my part to use the current color scheme and not just a grayscale map.
It's a good idea, but I would like to keep the current design too, so maybe we can implement it as a setting? So users can chose which style they prefer.

2024-06-19 16:36 UTC, EMREOYUN commented
I managed to add something like this because I couldn't manage how to reload CSS classes dynamically:
![image](https://github.com/GNimrodG/simrail-map-optimized/assets/35144629/3157ea73-1812-4515-87e3-48159c516cae)
If that is fine, I can commit these changes.

2024-06-19 16:43 UTC, GNimrodG commented
I think should be possible without the reload, just create an other class and toggle them based on the setting. I will look into it.

2024-06-20 07:23 UTC, GNimrodG requested changes
I suggested some changes that should fix the reload issue.
If you don't want to work with it anymore I will have time to fix these today after 6PM CEST.

2024-06-20 07:23 UTC, GNimrodG commented on smo-frontend/src/components/Settings.tsx
> +              </Typography>
If you use the `useLocalStorage` hook in the MainMap component this won't be necessary.

2024-06-20 07:23 UTC, GNimrodG commented on smo-frontend/src/components/MainMap.tsx
> +  );
this way it only updates the value when the page is loaded, use the `useLocalStorage` hook and it will update when you change the setting in the settings modal

2024-06-20 07:24 UTC, GNimrodG commented
Also you don't need to commit each file separately, you can include them in one commit ;)

2024-06-20 07:37 UTC, GNimrodG commented on smo-frontend/src/components/Settings.tsx
> +              </Typography>
Also pay attention to the formatting please, the closing tag should be at the same level as the opening tag

2024-06-20 08:02 UTC, EMREOYUN commented
> Also you don't need to commit each file separately, you can include them in one commit ;)

Since the other branch of mine has pending commits(personal changes), I do change files in Github Web Editor which does edit one file at the time.

2024-06-20 08:14 UTC, GNimrodG commented
> Since the other branch of mine has pending commits(personal changes), I do change files in Github Web Editor which does edit one file at the time.

You can use GitHub's web based VSCode (press `.` on the keyboard while the branch is open) then, there you can make and commit your changes.

2024-06-20 09:06 UTC, EMREOYUN commented on smo-frontend/src/components/MainMap.tsx
> +  );
The setting is updated, which is good. However, the main map does not refresh itself dynamically as of now.

2024-06-20 09:34 UTC, EMREOYUN commented
I wrote a custom TileLayer to refresh layers dynamically. Simple but effective.

2024-06-20 09:38 UTC, GNimrodG approved these changes
LGTM

2024-06-20 09:41 UTC, merged